language: node_js

cache:
  directories:
    - "node_modules"

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      node_js: stable
      script: npm install
    - stage: test
      node_js: stable
      script: npm test
    - stage: deploy
      node_js: stable
      deploy:
        provider: npm
        email: "ogustin.gagnon@gmail.com"
        api_key: ${API_KEY}
        on:
          branch: master
