language:
  node_js

notifications:
  email:
    recipients:
      - ogustin.gagnon@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
    - "node_modules"

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      node_js: stable
      script: npm install
    - stage: test
      node_js:
        - "9"
        - "8"
        - "7"
        - "6"
      script: npm test
    - stage: deploy
      node_js: stable
      script: npm version patch
      deploy:
        provider: npm
        email: "ogustin.gagnon@gmail.com"
        api_key: "47eda990-f5e3-4c71-b113-ae6d9bed0e8b"
        on:
          branch: master  # conditional release
