language:
  node_js

node_js:
  - stable

notifications:
  email:
    recipients:
      - ogustin.gagnon@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
    - "node_modules"

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      script: npm install
    - stage: test
      script: npm test
    - stage: deploy
      deploy:
        provider: npm
        email: "ogustin.gagnon@gmail.com"
        api_key: "47eda99bed0e8b"
        on:
          branch: master  # conditional release
